rover_interface_node:
  ros__parameters:
    port_name: COM3
    baud_rate: 9600
    received_msg_broadcast: /rover_receive
    transmit_request: /rover_transmitte
    received_msg_broadcast_qos: 10
    transmit_request_qos: 10