rover_interface_node:
  ros__parameters:
    port_name: COM3
    # port_name: COM20
    baud_rate: 9600
    received_msg_broadcast: /rover_receiver
    transmit_request: /rover_transmitter
    received_msg_broadcast_qos: 10
    transmit_request_qos: 10