@startuml

package "Kinematics" {
  [Inverse Kinematics]
  [Forward Kinematics]
}

package "Communication" {
  [Protocol Hub]
}

package "Data Fusion" {
  [Marvelmind Position Fusion]
}

package "Estimation" {
  [Pose Estimator]
}

package "Intelligence" {
  [Path Planning] #ff1919
  [Waypoint Controller] #ff1919
}

package "Command and Control" {
  [Rover Controller]
}

package "PHY Layer - Marvelmind" {
  [Marvelmind Beacon - Left]
  [Marvelmind Beacon - Right]
}

package "PHY Layer - Rover" {
  [Rover Interface]
}

package "PHY Layer - Sensors" {
  [Sonar Array] #ff1919
}


[Marvelmind Beacon - Left] -up-> [Marvelmind Position Fusion] : /position_measurement/left
[Marvelmind Beacon - Right] -up-> [Marvelmind Position Fusion] : /position_measurement/right

[Marvelmind Position Fusion] -up-> [Pose Estimator] : /position_measurement

[Pose Estimator] -down-> [Rover Controller] : /position_estimate

[Rover Controller] -down-> [Inverse Kinematics] : /relative_heading_setpoint

[Inverse Kinematics] -down-> [Protocol Hub] : /command

[Protocol Hub] -down-> [Rover Interface] : /rover_transmitter

[Protocol Hub] <-up- [Rover Interface] : /rover_receiver

[Protocol Hub] -up-> [Forward Kinematics] : /odometry

[Forward Kinematics] -up-> [Pose Estimator] : /relative_heading_estimate

[Path Planning] -down-> [Waypoint Controller] : /waypoint_list
[Waypoint Controller] -up-> [Path Planning] : /status
[Waypoint Controller] -down-> [Rover Controller] : /next_waypoint
[Waypoint Controller] <-up- [Rover Controller] : /status

[Sonar Array] -left-> [Path Planning] : /environment_info


@enduml